<?xml version="1.0" encoding="utf-8" standalone="yes"?>
 

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 1[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=5e28917a9e336f79</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 2[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=12ec92afe72af106</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 3[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=24a674830cd523e8</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 4[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=96a3b262d87fa251</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 5[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=35bc740c13c2d57d</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 6[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=957aff0b514c6431</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 7[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=649e0039fcd30f0c</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 8[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=4554f5c349c224b</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 9[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=af5046196cb981e5</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 10[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=baf77eb8c44d0665</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 11[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=9d8b28baee9606a3</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 12[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=bfb54d41615d4aa</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 13[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=df1adf3caa1ed7a2</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 14[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=5f5462caf6ae2bf7</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 15[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=70207ce4198cc7ea</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 16[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=bf4105758a73d7a1</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 17[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=ccbdfa2c82150c</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 18[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=7c206e982aec3059</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 19[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=79e28452d83be407</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 20[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=5afff869e6ebb20d</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 21[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=ec77918feec25fdb</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 22[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=db78f35eeda067e7</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 23[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=1ac9491bb128d925</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 24[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=bdd0abd1bac0c550</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 25[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=6ac7585ffa0cc959</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 26[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=4761961856123b66</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 27[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=241987145bd82c01</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 28[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=aa9d67341c61ad13</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 29[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=dffe6329f1dc1a43</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 30[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=cd82bf1b35e269d7</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 31[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=1330094450d3d2b0</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 32[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=815c3c61156ac21f</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 33[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=628eeda8a2190c45</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 34[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=14a093de23790548</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 35[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=cbe191ff4e71ea67</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 36[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=1f4b4328f48e008</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 37[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=c5f859fd686e61cf</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

<item>
<title>[COLOR gold][B]Power Rangers S.P.D 38[/B][/COLOR]</title>
<link>http://www.blogger.com/video-play.mp4?contentId=ca8c951f12ef6d93</link>
<thumbnail>http://i.imgur.com/fIWoQwF.jpg</thumbnail>
<fanart>https://goo.gl/dRv3iL</fanart>
</item>

